name: Build and Publish Docker Image
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: moviepediafilms/share-interceptor
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "latest,${{ steps.date.outputs.date }}"
  deploy:
    needs: create-tag
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          debug: ${{ secrets.DEBUG }}
          script: |
            docker pull ghcr.io/moviepediafilms/share-interceptor:latest
